version: '3.1'

services:
    database:
        image: postgres:12
        restart: always
        environment: 
            POSTGRES_PASSWORD: clementine
        ports: 
            - 5432:5432
        volumes: 
            - pgdata:/var/lib/postgresql/data
    redis:
        image: bitnami/redis:latest
        restart: always
        environment: 
            ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - 6379:6379
        volumes:
            - redisdata:/bitnami/redis/data

volumes:
    pgdata:
        driver: local
    redisdata:
        driver: local