version: '3.1'

services:
    database:
        image: postgres:12
        restart: always
        environment: 
            POSTGRES_PASSWORD: clementine
        ports: 
            - 5432:5432
        volumes: 
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
        driver: local